services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  backend:
    build: ../backend
    volumes:
      - static_volume:/test-task/backend/static/
      - media_volume:/test-task/backend/media/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: "./entrypoint.sh"
    command: poetry run python3 manage.py runserver 0.0.0.0:8000 --insecure

volumes:
  db_volume:
  static_volume:
  media_volume: